### ISSUE TITLE
Opening Bitcurator with VirtualBox

### ISSUE THREAD

**Issue by MelissaRo** [BitCurator/bitcurator-distro-main#103]
I have no experience with either of these systems, and every time I try to open BitCurator I get this error- Failed to open a session for the virtual machine BitCurator-1.21. No error info.

Under Settings and Storage there is an error sign under Controller. Does anyone have any idea what this means and what I can do?

**Comment by kamwoods** [comment]
Closing. Outdated, unrelated to this repo.
