### ISSUE TITLE
BitCurator final report generator sometimes hangs / never completes

### ISSUE THREAD

**Issue by carlwilson** [BitCurator/bitcurator-distro-main#33]
This is an awkward issue as the behaviour isn't repeatable.  During testing the report generation process occasionally hangs, the symptoms are:
- no new files created in the excel file directory
- activity bar still in motion, so no visual indication of a problem
- cancel button no longer responds
- close button no longer responds

The only way to stop the process was issuing a kill command from the terminal.
During testing I waited several hours to make sure that the process wasn't just taking a long time for some reason.
The test environment had 16GB of RAM so lack of memory issues unlikely to be the sole cause.

**Comment by kamwoods** [comment]
Updates for 1.8.16 have addressed the most frequent cause of this issue - mishandling of malformed Unicode. Closing; future enhancements for improved feedback should be addressed in new issues.
